config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :random, to: 'articles#random'
  get :articles, to: 'articles#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'curb'

class Article
  API_URL = "https://www.wikihow.com/api.php?".freeze
  # These categories return incomplete pages
  BAD_CATS = ['Category:Stub', 'Category:Articles in Quality Review']

  def self.fetch(url)
    curl = Curl::Easy.http_get(url) do |c|
      c.follow_location = true
      c.max_redirects = 3
    end

    curl.body_str
  end

  def self.random_urls
    response = Article.random_pages
    active_pages = response.reject do |page|
      cats = page["categories"].present?
    end

    active_pages.map do |page|
      # render mobile view
      page["fullurl"].sub('www', 'm')
    end.take(3)
  end

  def self.random_pages(limit = 10)
    params = {
      action: 'query',
      generator: 'random',
      grnnamespace: 0,
      grnlimit: limit,
      prop: 'info|categories',
      inprop: 'url',
      redirects: true,
      # Only lists categories if they're bad
      clcategories: BAD_CATS.join('|'),
      format: 'json'
    }
    response = Curl.get(API_URL + params.to_query).body_str
    json = JSON.parse(response)
    json["query"]["pages"].values
  end

  # Category:Stub
  # Category:Articles in Quality Review

  # def title
  #   document.css('div#intro h1 a').text
  # end

  # def headers
  #   document_sections.flat_map do |section|
  #     section.css('span.mw-headline').text
  #   end.reject(&:blank?)
  # end

  # def steps
  #   document_sections.flat_map do |section|
  #     section.css('div.section_text ol li').flat_map do |step|
  #       step.css('div.step').to_s
  #     end
  #   end.reject(&:blank?)
  # end

  # def images
  #   document_sections.flat_map do |section|
  #     section.css('div.section_text ol li').flat_map do |step|
  #       img = step.css('div.mwimg img')
  #       img.attr('data-src').try(:text) if img.present?
  #     end
  #   end.reject(&:blank?)
  # end

  # private

  # def document
  #   @document ||= Nokogiri::HTML(open(url))
  # end

  # def document_sections
  #   @document_sections ||= document.css('div#bodycontents div.steps')
  # end
end

app/models/combined_article.rb
class CombinedArticle
  include ActiveModel::Model

  def initialize(ids)
    articles = Article.where(id: ids)
    @a = articles[0]
    @b = articles[1]
    @c = articles[2]
  end

  def title
    @a.title
  end

  def sections
    secs = @a.headers
    steps_per = steps.length / secs.length
    steps_ary = steps
    images_ary = images

    secs.map.with_index do |section, i|
      {
        number: i + 1,
        header: section,
        steps: Array.new(steps_per.to_i) do |i|
          {
            number: i + 1,
            content: steps_ary.pop,
            image: images_ary.pop
          }
        end
      }
    end
  end

  def steps
    @steps ||= @b.steps
  end

  def images
    @images ||= @c.images
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def random
    render json: Article.random_urls
  end

  def show
    article = Article.fetch(params[:url])
    render body: article
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Wikihow</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="mediawiki ltr  sitedir-ltr">
  <div id="header_outer" role="navigation">
    <div id="header">
      <ul id="actions" role="menubar" aria-label="Header navigation">
        <li id="nav_explore_li" class="nav_item" role="menuitem" aria-labelledby="nav_explore" style="width: 175px; text-align: center;">
          <div class="nav_icon"></div>
          <%= form_tag random_path, method: :get do %>
            <button type="submit" class="nav" id="nav_explore" style="width: 100%; font-size: 18px; border:0; padding:40px 0 0 0; background:none; cursor: pointer;">
              RANDOM OUCH
            </button>
          <% end %>
        </li>
      </ul>
      <!--end actions-->
      <a href="<%= random_path %>" style="display:block; padding-top: 10px;">
        <%= image_tag 'logo' %>
      </a>
      <!--       <form id="bubble_search" name="search_site" action="/wikiHowTo" method="get" role="search">
        <input type="text" class="search_box" name="search" value="" placeholder="to do anything..." x-webkit-speech />
        <input type="submit" value="Search" id="search_site_bubble" class="search_button" />
      </form> -->
    </div>
    <!--end header-->
    <div id="header_after"></div>
  </div>
  <!--end header-outer-->
  <div id="main_container">
    <div id="header_space"></div>
    <div id="main">
      <div id="actionbar" class="" role="navigation">
      </div>
      <!--end actionbar-->
      <div id="container" class="">
        <div id="article_shell">
          <div id="article" role="main">
            <div id="bodycontents">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>